import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          'flex flex-col bg-[url(/images/background-image.png)] bg-center bg-cover'
        }
      >
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
